### ISSUE TITLE
FeedParser should support parsing already retrieved feed data

### ISSUE THREAD

**Issue by johnl** [arttu/feed_parser#1]
Currently expects to be passed a url, but it'd be handy to be able to just pass it data if you've already got it. You'd actually be able to do this with the Feed class if it didn't depend on FeedParser having been initialized.

**Comment by arttu** [comment]
As I just commented on the #1, I'm sorry about the delayed answer and I finally try to address your wishes tomorrow.

**Comment by johnl** [comment]
Actually, I fixed this on my own fork - not sure why I didn't issue a pull request though.

I also fixed a couple of other bugs too.
